### PR TITLE
chore: Unified disabled & loading states

### PR DESCRIPTION
**Pull request by gretanausedaite**
Moving [css change](https://github.com/iTwin/iTwinUI/pull/756/commits/e012ec3353a875ce73ab7a5a54b90b752cdde5ea) into react.

New features in react:
- Tile status and loading stated will be added in other PR.
- Table row loading state will be added in other PR.

### CODE REVIEW

**Review by mayank99 — APPROVED** [review]
PR title should probably be "chore" or at least "fix", because this is not a feature and there is no code change.

**Review by r100-stack — COMMENTED** [review]
Sorry for the slight delay in reviewing this. I saw your PR yesterday, reviewed part of it yesterday to continue it today, but just noticed it was already merged.

One observation I had: Is the text of the table's disabled row expected to be in italics? Because in the demo CSS website for PR [#765](https://github.com/iTwin/iTwinUI/pull/765), the table's disabled row seems to have normal text.

image

Also noticed that in the demo website, it is using `aria-disabled=true` but in react we are using `.iui-disabled`.

##### CSS
image

##### React
image

Or maybe I'm missing something?

**Comment by gretanausedaite** [comment]
> One observation I had: Is the text of the table's disabled row expected to be in italics? Because in the demo CSS website for PR [#765](https://github.com/iTwin/iTwinUI/pull/765), the table's disabled row seems to have normal text.
> 
> image
> 
Disabled table row text in my PR screenshots is normal. Did you run `yarn` in your local machine (if you were running this branch locally)?

> Also noticed that in the demo website, it is using `aria-disabled=true` but in react we are using `.iui-disabled`.
> 
> ##### CSS
> image
> 
> ##### React
> image
> 
> Or maybe I'm missing something?

I have aria-disabled=true when I run dev environment locally. 
image

**Comment by rohan-kadkol** [comment]
Ohh, yes, sorry, I tested from a different commit/branch since I saw no code changes (but I forgot about the updated dependency change). Everything LGTM now.

**Pull request merged**
