### PR TITLE
chore(v1): Updating visual changes and unit tests

### PR DESCRIPTION
**Pull request by adamhock**
During the latest merge from `main` to `itwinui-css-v1`, there were a few failing images and unit tests

The visual changes can be explained by the following:
  - [Variables PR](https://github.com/iTwin/iTwinUI/pull/718) 
    - changes to `border-radius` on `iui-menu-item`, `background-color` on `iui-date-range`, and `line-height` on multiple items
  - #812 
    - font changes

The unit test changes can be explained by the following:
  - #749 
    - renaming `iui-row` to `iui-table-row`

### CODE REVIEW

**Review by gretanausedaite — APPROVED** [review]

**Comment by rohan-kadkol** [comment]
I'm slightly unsure whether this is already fixed. Because I think the additions you made in the PR are already there. Also yesterday, I worked on resolving the merge conflicts between merging `itwinui-css-v1` and `main` ([commit](https://github.com/iTwin/iTwinUI-react/pull/733/commits/fbb3659bf428f67837ca48b2497e411efb537b43)). So maybe some of the tests are already fixed with that commit?

You can confirm this by seeing the current code of [Table.test.tsx (1248-1614)](https://github.com/iTwin/iTwinUI-react/blob/itwinui-css-v1/packages/iTwinUI-react/src/core/Table/Table.test.tsx#L1248-L1614) in `itwinui-css-v1 branch` and comparing it with your code

**Comment by adamhock** [comment]
Updating the branch fixed the unit tests, but the visual tests are still broken

**Comment by mayank99** [comment]
> Updating the branch fixed the unit tests, but the visual tests are still broken

What do you mean by "broken"? If the image updates in this PR are making the tests pass in CI (you can manually run `CI` on this branch in the [Actions tab](https://github.com/iTwin/iTwinUI-react/actions/workflows/build.yml)), then lets merge it.

**Comment by adamhock** [comment]
> > Updating the branch fixed the unit tests, but the visual tests are still broken
> 
> What do you mean by "broken"? If the image updates in this PR are making the tests pass in CI (you can manually run `CI` on this branch in the [Actions tab](https://github.com/iTwin/iTwinUI-react/actions/workflows/build.yml)), then lets merge it.

I misspoke. By "broken" I mean "needs updating".

I wanted to make sure Rohan understood the changes and approved them before merging.

**Comment by rohan-kadkol** [comment]
I ran the [CI manually](https://github.com/iTwin/iTwinUI-react/actions/runs/3114469820/jobs/5050347211). Looks like 3 tests are still failing:



image

image
image

**Comment by mayank99** [comment]
> I misspoke. By "broken" I mean "needs updating".

> I ran the [CI manually](https://github.com/iTwin/iTwinUI-react/actions/runs/3114469820/jobs/5050347211). Looks like 3 tests are still failing:

Yeah so lets update those in this PR and merge it.

**Comment by adamhock** [comment]
I've updated the Dialog images, but I can't reproduce the "Select Truncate Middle Text" image mismatch

**Review by r100-stack — APPROVED** [review]
I re-ran the [CI (#3277)](https://github.com/iTwin/iTwinUI-react/actions/runs/3114965535) and all tests passed :slightly_smiling_face:

**Pull request merged**
