### PR TITLE
feat!: Update itwinui-css to 1.0.0.dev.10

### PR DESCRIPTION
**Pull request by veekeys**
- Updated css import for build to pass

Todo:
- [x] `Alert` https://github.com/iTwin/iTwinUI/pull/639#issuecomment-1148553848
- [ ] `Inputs` revalidate multiple imports https://github.com/iTwin/iTwinUI/pull/639#issuecomment-1148553848
- [ ] Validate all the visual changes with updating test images

- **Alert:** Class name & specificity refactor [commit](https://github.com/iTwin/iTwinUI/pull/639/commits/6efd8e5f93ed57867287dd632b7b93899b2b730b)
	- `iui-button iui-borderless iui-small` -> `iui-alert-button`
	- `iui-button-icon` -> `iui-alert-button-icon`
	- `iui-alert iui-informational` -> `iui-alert-informational` (same with all the statuses)

### CODE REVIEW

**Comment by adamhock** [comment]
### **#749 Table Refactor**
- **Data Attribute**
  - `iui-condensed/extra-condensed` replaced with `data-iui-size="condensed/extra-condensed"`
  - `iui-selected` replaced with `aria-selected="true"`
    - `iui-table-body` elements that contain selectable rows now have `aria-multiselectable="true"`
  - `iui-disabled` replaced with `aria-disabled="true"`
- **Class name changes**
  - `iui-paginator-*` changed to `iui-table-paginator-*`
  - `iui-column-filter` changed to `iui-table-column-filter`
  - `iui-filter-button` changed to `iui-table-filter-button`
  - `iui-resizer-*` changed to `iui-table-resizer-*`
  - `iui-sort` changed to `iui-table-sort`
  - `iui-reorder-bar-*` changed to `iui-table-reorder-bar-*`
  - `iui-expanded-content` changed to `iui-table-expanded-content`
  - `iui-row-*` changed to `iui-table-row-*`
  - `iui-cell-*` changed to `iui-table-cell-*`

**Review by gretanausedaite — COMMENTED** [review]
- [x] `Button`

**Comment by veekeys** [comment]
Tasks with current css dev package

- [ ] `Header`
- [ ] `Wizard`
- [ ] `UserIcon`
- [ ] `RadioTileGroup`

**Comment by mayank99** [comment]
After updating this branch, some of the tests are failing. Whoever worked on and/or reviewed #810 and #811 should update the tests to pass. @iTwin/itwinui-react-1 @iTwin/itwinui-react-2

**Comment by mayank99** [comment]
@rohan-kadkol  You need to resolve merge conflicts in this PR that are resulting from your shift-click changes.

**Comment by rohan-kadkol** [comment]
> @rohan-kadkol You need to resolve merge conflicts in this PR that are resulting from your shift-click changes.

Fixed the three files that had merge conflicts:

image

For the two `Dialog` related images (first two files), I just chose the version on the main branch

For `Table.test.tsx` (3rd file), I fixed it by:
* Changing selected state checks from class name should have `.iui-selected` to should have attribute `aria-selected = true`
* Added shift click tests checks

**Pull request merged**
