### PR TITLE
chore: Publish visual tests result artifact

### PR DESCRIPTION
**Pull request by gretanausedaite**
Added action to publish tests results.

### CODE REVIEW

**Comment by bentleyvk** [comment]
No no no 😀 just do that in that PR you are working on

**Comment by mayank99** [comment]
This will become out of date real quick as #640 is near completion. So I can just add it in there instead.

**Comment by veekeys** [comment]
> This will become out of date real quick as #660 is near completion. So I can just add it in there instead.

Wouldnt you then just need to change the path..?

**Comment by gretanausedaite** [comment]
This will be added with #660

**Pull request closed without merging**
